// Copyright (c) 2026 Steven Verhelle (enqack)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

package magelib

import (
	"bytes"
	"os"
	"os/exec"
	"testing"
)

// requireTool fails - never skips - when a tool the test needs is
// absent. An absent test and a passing test are indistinguishable in a
// summary line, and this suite's whole subject is a formatter, so a
// missing formatter must be loud.
func requireTool(t *testing.T, name string) {
	t.Helper()
	if _, err := exec.LookPath(name); err != nil {
		t.Fatalf("%s not on PATH: %v - run inside 'nix develop'", name, err)
	}
}

// generatedGoimportsDirty reproduces MAGELIB-DIV-007's exact defect in
// miniature: it is gofmt-CLEAN and goimports-DIRTY.
//
// The distinction is the whole entry. gofmt sorts imports within a
// parenthesised group and this one is already sorted, so gofmt has
// nothing to say. goimports additionally SPLITS stdlib from
// third-party, and protoc-gen-go interleaves them - so goimports
// rewrites a file its generator considers finished. MEASURED on the
// real thing: 9 of 9 generated .pb.go files in gapi are gofmt-clean
// and goimports-dirty.
//
// magelib ships no generated Go of its own, which is why a fixture is
// the only way this repo can observe a defect whose blast radius is
// entirely in its consumers - the same shape MAGELIB-DIV-001 named, a
// rule its author is not subject to.
const generatedGoimportsDirty = `// Code generated by protoc-gen-go. DO NOT EDIT.

package p

import (
	"fmt"
	"google.golang.org/protobuf/runtime/protoimpl"
	"os"
)

var _ = fmt.Sprint
var _ = os.Getenv
var _ = protoimpl.X
`

// handWrittenUnformatted is unformatted in ways plain gofmt fixes, so
// it can prove Fmt still does its job.
const handWrittenUnformatted = `package p

func G()  {
x:=1
_=x
}
`

// TestFmtLeavesGeneratedFilesByteIdentical is MAGELIB-DIV-007's gate.
//
// The defect: Fmt wrote with goimports while the Lint check read with
// gofmt, over the same file set. Generated protobuf output is
// gofmt-clean by construction but not goimports-clean, so `mage lint`
// would fail on ONE hand-written file, tell the developer to run
// `mage fmt`, and that command would rewrite every generated .pb.go in
// the repo - churn they did not author, which `mage proto` reverts on
// the next regeneration. A stable, silent loop: nothing is ever wrong
// and the diff never goes away.
//
// The fix is direction C (operator decision 22): Fmt uses gofmt, so
// the two tools agree and generated output is left alone BY
// CONSTRUCTION rather than by an exclusion list. That is why this test
// needs no generated-file predicate to pass - if it ever starts
// needing one, the fix has drifted back toward a carve-out.
//
// BOTH halves are required. Asserting only that the generated file is
// untouched would be satisfied by a Fmt that formats nothing at all.
func TestFmtLeavesGeneratedFilesByteIdentical(t *testing.T) {
	requireTool(t, "gofmt")
	writeTree(t, map[string]string{
		"gen.pb.go": generatedGoimportsDirty,
		"hand.go":   handWrittenUnformatted,
	})

	if err := Fmt(); err != nil {
		t.Fatalf("Fmt: %v", err)
	}

	after, err := os.ReadFile("gen.pb.go")
	if err != nil {
		t.Fatalf("read generated: %v", err)
	}
	if !bytes.Equal([]byte(generatedGoimportsDirty), after) {
		t.Fatalf("Fmt rewrote a generated file that its generator considers finished.\n"+
			"want (byte-identical):\n%s\ngot:\n%s", generatedGoimportsDirty, after)
	}

	// The converse, and it is not decoration: without it the assertion
	// above is satisfied by a Fmt that does nothing, which would pass
	// this gate while silently removing formatting from the ecosystem.
	hand, err := os.ReadFile("hand.go")
	if err != nil {
		t.Fatalf("read hand-written: %v", err)
	}
	if bytes.Equal([]byte(handWrittenUnformatted), hand) {
		t.Fatal("Fmt left an unformatted hand-written file untouched; " +
			"a Fmt that formats nothing satisfies the generated-file " +
			"assertion trivially")
	}
	if !bytes.Contains(hand, []byte("x := 1")) {
		t.Fatalf("hand-written file was not gofmt-formatted:\n%s", hand)
	}
}
