package magelib

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
)

// generatedMarker is the Go convention for machine-written source, as
// specified by the go generate documentation and honoured by gofmt,
// golangci-lint and gosec. Several rules in this library exempt
// generated code, so they need a machine-checkable definition of
// "generated" and this is the only one the ecosystem agrees on.
//
// Known gap, deliberate: gopy emits a NON-standard header ("File is
// generated by gopy. Do not edit." inside a block comment), so its
// output - gapi's adk/python/gapi/native/adk.go at 1312 lines - is not
// recognised here. Special-casing one generator's prose would make
// every consuming gate carry a list of vendor spellings that nobody
// maintains. Such a file belongs in a Skip, which is the mechanism for
// "the rule does not apply", NOT in a waiver list, which is the
// mechanism for "the rule applies and is being violated". See
// CheckFileLength and GAPI-DIV-044.
//
// Detection is by this HEADER and never by the .pb.go suffix. The
// suffix names one generator; the header names the property, and gopy
// is the standing proof that the two are not the same set.
var generatedMarker = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)

// IsGenerated reports whether the file at path carries the standard
// generated marker. A file that cannot be read is an ERROR, never a
// false: a caller that treats "unreadable" as "hand-written" would
// process a file it could not see, and one that treats it as
// "generated" would silently exempt it. Neither is a decision this
// function is entitled to make for the caller.
//
// STATE OF WIRING, stated because a doc comment naming a caller that
// does not exist is this ecosystem's most common defect: the two gates
// that exempt generated code today - CheckFileLength and
// CheckLicenseHeaders - consume the unexported isGenerated directly,
// because they have already read the file and a second read would be
// waste. NOTHING CALLS THIS EXPORTED FORM YET. It exists because
// MAGELIB-DIV-007 must classify files it has not read, and that entry
// is open pending an operator decision between its two directions. If
// -007 closes by some other route, this function has no caller and
// should be deleted rather than left as surface.
//
// What is genuinely shared today is the DEFINITION, not this wrapper:
// one marker and one scanner, so two gates cannot drift apart on what
// "generated" means - the failure MAGELIB-DIV-003 recorded when a
// check and its enforcing twin read two declarations.
func IsGenerated(path string) (bool, error) {
	// #nosec G304 -- the caller names a path inside the repo it was
	// invoked in; this function reads, classifies and never writes.
	data, err := os.ReadFile(path)
	if err != nil {
		return false, fmt.Errorf("generated check: read %s: %w", path, err)
	}
	return isGenerated(data), nil
}

// isGenerated reports whether the file carries the standard generated
// marker above its first line of code. The marker is only looked for in
// the leading comment block, per the convention that it precedes the
// package clause: scanning the whole file would let a doc comment that
// merely quotes the marker exempt hand-written code.
func isGenerated(data []byte) bool {
	for _, line := range bytes.Split(data, []byte("\n")) {
		trimmed := bytes.TrimSpace(line)
		if len(trimmed) == 0 {
			continue
		}
		if !bytes.HasPrefix(trimmed, []byte("//")) {
			return false // reached code; nothing above it was the marker
		}
		if generatedMarker.Match(trimmed) {
			return true
		}
	}
	return false
}
