// Copyright (c) 2026 Steven Verhelle (enqack)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

package magelib

import (
	"bytes"
	"regexp"
)

// generatedMarker is the Go convention for machine-written source, as
// specified by the go generate documentation and honoured by gofmt,
// golangci-lint and gosec. Several rules in this library exempt
// generated code, so they need a machine-checkable definition of
// "generated" and this is the only one the ecosystem agrees on.
//
// Known gap, deliberate: gopy emits a NON-standard header ("File is
// generated by gopy. Do not edit." inside a block comment), so its
// output - gapi's adk/python/gapi/native/adk.go at 1312 lines - is not
// recognised here. Special-casing one generator's prose would make
// every consuming gate carry a list of vendor spellings that nobody
// maintains. Such a file belongs in a Skip, which is the mechanism for
// "the rule does not apply", NOT in a waiver list, which is the
// mechanism for "the rule applies and is being violated". See
// CheckFileLength and GAPI-DIV-044.
//
// Detection is by this HEADER and never by the .pb.go suffix. The
// suffix names one generator; the header names the property, and gopy
// is the standing proof that the two are not the same set.
var generatedMarker = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)

// There is deliberately NO exported path-taking IsGenerated here.
//
// One existed briefly, written for MAGELIB-DIV-007 on the assumption
// that entry would need to classify files it had not yet read. It
// resolved the other way (operator decision 22): making Fmt and the
// Lint check agree on gofmt leaves generated output alone BY
// CONSTRUCTION, so no formatting code needs a predicate at all. An
// exported symbol with no caller is this ecosystem's most common
// defect, so it was removed rather than kept as surface.
//
// What is shared is the DEFINITION below - one marker and one scanner,
// consumed by CheckFileLength and CheckLicenseHeaders, which have both
// already read the file. Two gates, one definition, so they cannot
// drift on what "generated" means: the failure MAGELIB-DIV-003
// recorded when a check and its enforcing twin read two declarations.

// isGenerated reports whether the file carries the standard generated
// marker above its first line of code. The marker is only looked for in
// the leading comment block, per the convention that it precedes the
// package clause: scanning the whole file would let a doc comment that
// merely quotes the marker exempt hand-written code.
func isGenerated(data []byte) bool {
	for _, line := range bytes.Split(data, []byte("\n")) {
		trimmed := bytes.TrimSpace(line)
		if len(trimmed) == 0 {
			continue
		}
		if !bytes.HasPrefix(trimmed, []byte("//")) {
			return false // reached code; nothing above it was the marker
		}
		if generatedMarker.Match(trimmed) {
			return true
		}
	}
	return false
}
