package magelib

import (
	"os"
	"strings"
	"testing"
)

// headered renders a Go file already carrying the notice, built by the
// inserter itself so the "green" half of every red/green pair is
// exactly what the sweep would have produced.
func headered(t *testing.T, body string) string {
	t.Helper()
	return string(insertNotice([]byte(body), goNotice(t)))
}

// TestCheckLicenseHeadersRedGreen is the hypothesis this gate was built
// to falsify: a pair differing ONLY in one file's header proves the
// gate discriminates. Both halves are required. The red half alone
// could be a gate that fails on everything, and the green half alone
// could be a gate that fails on nothing - and a gate that cannot fail
// reports success.
func TestCheckLicenseHeadersRedGreen(t *testing.T) {
	const body = "package p\n\nfunc F() {}\n"

	t.Run("missing the notice fails", func(t *testing.T) {
		writeTree(t, map[string]string{"a.go": body})
		err := CheckLicenseHeaders(testLicense())
		if err == nil {
			t.Fatal("a file with no notice was reported clean")
		}
		if !strings.Contains(err.Error(), "a.go") {
			t.Fatalf("error does not name the file: %v", err)
		}
		// The operator must be told what fixes it; a gate that reports
		// 400 files without naming the remedy gets fixed by hand.
		if !strings.Contains(err.Error(), "licenseAdd") {
			t.Fatalf("error does not name the remedy: %v", err)
		}
	})

	t.Run("carrying the notice passes", func(t *testing.T) {
		writeTree(t, map[string]string{"a.go": headered(t, body)})
		if err := CheckLicenseHeaders(testLicense()); err != nil {
			t.Fatalf("a file carrying the notice failed: %v", err)
		}
	})
}

// TestCheckLicenseHeadersRejectsAWrongYear: the year is per repo and
// must be exact-matchable, which is the whole reason it is a constant
// rather than time.Now().Year(). If the check accepted any year it
// would have stopped checking that field, and a mangled notice would
// pass.
func TestCheckLicenseHeadersRejectsAWrongYear(t *testing.T) {
	writeTree(t, map[string]string{
		"a.go": headered(t, "package p\n"),
	})
	wrongYear := testLicense()
	wrongYear.Year = 2025
	if err := CheckLicenseHeaders(wrongYear); err == nil {
		t.Fatal("a notice bearing a different year was accepted")
	}
}

// TestCheckLicenseHeadersIgnoresANoticeBelowTheCode. The gate certifies
// that a file's licence status is unambiguous to a reader who opens it,
// and a reader forms that judgement from the top. A whole-file search
// would also accept a notice sitting inside a string literal.
func TestCheckLicenseHeadersIgnoresANoticeBelowTheCode(t *testing.T) {
	buried := "package p\n\nconst legal = `" + goNotice(t) + "`\n"
	writeTree(t, map[string]string{"a.go": buried})
	if err := CheckLicenseHeaders(testLicense()); err == nil {
		t.Fatal("a notice below the package clause was accepted as a header")
	}
}

// TestCheckLicenseHeadersSkipsGeneratedFiles. Operator decision 19:
// generated code gets no per-file header, because a hand-maintained
// header there is wiped by the next regeneration - the obvious approach
// is the one that cannot work. A paragraph in each repo's LICENSE
// covers it instead.
func TestCheckLicenseHeadersSkipsGeneratedFiles(t *testing.T) {
	writeTree(t, map[string]string{
		"ping.pb.go": "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage p\n",
	})
	if err := CheckLicenseHeaders(testLicense()); err != nil {
		t.Fatalf("a generated file was policed: %v", err)
	}
}

// TestCheckLicenseHeadersDetectsGeneratedByHeaderNotSuffix is the
// distinction MAGELIB-DIV-007's exit insists on, and it is not
// academic: gopy output is generated too and carries a non-standard
// header, so a suffix test and a header test classify different sets.
// A hand-written file merely NAMED like generated output is still
// hand-written.
func TestCheckLicenseHeadersDetectsGeneratedByHeaderNotSuffix(t *testing.T) {
	writeTree(t, map[string]string{"impostor.pb.go": "package p\n"})
	err := CheckLicenseHeaders(testLicense())
	if err == nil {
		t.Fatal("a hand-written file was exempted on its .pb.go suffix alone")
	}
	if !strings.Contains(err.Error(), "impostor.pb.go") {
		t.Fatalf("error does not name the file: %v", err)
	}
}

// TestCheckLicenseHeadersScope pins operator decision 18. The excluded
// types are excluded for stated reasons - no comment syntax, thin
// expression, or covered by the repo LICENSE - and a gate that quietly
// widened its scope would produce a diff nobody authorised across a
// 400-file sweep.
func TestCheckLicenseHeadersScope(t *testing.T) {
	writeTree(t, map[string]string{
		"data.json":         `{"a":1}`,
		"ledger.jsonl":      `{"id":"X"}`,
		"README.md":         "# hi\n",
		"buf.gen.yaml":      "version: v1\n",
		"go.mod":            "module example.com/m\n",
		"vendor/dep.go":     "package dep\n",
		".venv/lib.py":      "x = 1\n",
		"node_modules/a.go": "package a\n",
	})
	if err := CheckLicenseHeaders(testLicense()); err != nil {
		t.Fatalf("an out-of-scope file was policed: %v", err)
	}
}

// TestCheckLicenseHeadersPolicesEveryInScopeType is the converse, and
// it is the half that would otherwise rot. Without it, a typo in
// licenseCommentPrefix would silently drop a language from the sweep
// and the scope test above would still pass - the gate would go quiet,
// and quiet is indistinguishable from clean.
func TestCheckLicenseHeadersPolicesEveryInScopeType(t *testing.T) {
	for ext := range licenseCommentPrefix {
		t.Run(ext, func(t *testing.T) {
			writeTree(t, map[string]string{"f" + ext: "x\n"})
			err := CheckLicenseHeaders(testLicense())
			if err == nil {
				t.Fatalf("%s is in licenseCommentPrefix but was not policed", ext)
			}
			if !strings.Contains(err.Error(), "f"+ext) {
				t.Fatalf("error does not name f%s: %v", ext, err)
			}
		})
	}
}

// TestCheckLicenseHeadersReportsEveryViolation: the first run in each
// repo names hundreds of files, and a gate that stopped at the first
// would turn one sweep into hundreds of build cycles.
func TestCheckLicenseHeadersReportsEveryViolation(t *testing.T) {
	writeTree(t, map[string]string{
		"a.go":      "package p\n",
		"pkg/b.py":  "x = 1\n",
		"pkg/c.sh":  "echo hi\n",
		"pkg/ok.go": headered(t, "package p\n"),
	})
	err := CheckLicenseHeaders(testLicense())
	if err == nil {
		t.Fatal("no error")
	}
	for _, want := range []string{"a.go", "pkg/b.py", "pkg/c.sh"} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("error did not name %s: %v", want, err)
		}
	}
	if strings.Contains(err.Error(), "pkg/ok.go") {
		t.Fatalf("a headered file was reported: %v", err)
	}
}

// TestAddLicenseHeadersReportsWhatItModified is a HARD REQUIREMENT of
// the sweep, not a convenience. `git add -A` is banned twice over, so
// the add list must be built from the tool's output; a sweeper that
// reported nothing would leave a wildcard as the only practical option.
func TestAddLicenseHeadersReportsWhatItModified(t *testing.T) {
	writeTree(t, map[string]string{
		"a.go":      "package p\n",
		"b.py":      "x = 1\n",
		"done.go":   headered(t, "package p\n"),
		"skip.json": "{}",
	})
	modified, err := AddLicenseHeaders(testLicense())
	if err != nil {
		t.Fatalf("add: %v", err)
	}
	got := strings.Join(modified, ",")
	if got != "a.go,b.py" {
		t.Fatalf("modified list is %q, want \"a.go,b.py\" - the git add line is built from this", got)
	}
	if err := CheckLicenseHeaders(testLicense()); err != nil {
		t.Fatalf("the check still fails after the sweep it prescribes: %v", err)
	}
}

// TestAddLicenseHeadersIsIdempotent. A second run must stage nothing.
// Without this a re-run would rewrite every file, and the sweep would
// be unrepeatable in a silo where it may have to be redone after a
// rebase.
func TestAddLicenseHeadersIsIdempotent(t *testing.T) {
	writeTree(t, map[string]string{"a.go": "package p\n\nfunc F() {}\n"})
	if _, err := AddLicenseHeaders(testLicense()); err != nil {
		t.Fatalf("first add: %v", err)
	}
	first, err := os.ReadFile("a.go")
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	modified, err := AddLicenseHeaders(testLicense())
	if err != nil {
		t.Fatalf("second add: %v", err)
	}
	if len(modified) != 0 {
		t.Fatalf("second run modified %v", modified)
	}
	second, err := os.ReadFile("a.go")
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if string(first) != string(second) {
		t.Fatalf("second run changed the file:\n%s\n---\n%s", first, second)
	}
}

// TestLicenseConfigRejectsBadInput. Each of these would otherwise be
// written into every file in the repo by a tool that touched 400 of
// them, and the copyright sign is the one non-ASCII character a notice
// specifically invites.
func TestLicenseConfigRejectsBadInput(t *testing.T) {
	cases := map[string]LicenseConfig{
		"no holder":        {Holder: "", Year: 2026},
		"zero year":        {Holder: "A", Year: 0},
		"non-ascii holder": {Holder: "Steven Verhelle \u00a9", Year: 2026},
	}
	for name, cfg := range cases {
		t.Run(name, func(t *testing.T) {
			if _, err := cfg.Notice(".go"); err == nil {
				t.Fatal("accepted")
			}
			if err := CheckLicenseHeaders(cfg); err == nil {
				t.Fatal("gate ran on an unenforceable configuration")
			}
		})
	}
}

// TestNoticeRejectsAnUnknownExtension: a caller receiving "" would
// write a file with no notice and no complaint.
func TestNoticeRejectsAnUnknownExtension(t *testing.T) {
	if _, err := testLicense().Notice(".rs"); err == nil {
		t.Fatal("an unknown extension rendered a notice")
	}
}

// TestNoticeCarriesAllThreeParts. Operator decision 17 takes the
// copyright line, Exhibit A verbatim AND the SPDX identifier, because
// they answer to different readers: section 1.4 names Exhibit A as what
// makes a file Covered Software, while scanners read the identifier.
// Dropping either half silently would satisfy neither reader fully.
func TestNoticeCarriesAllThreeParts(t *testing.T) {
	n, err := testLicense().Notice(".go")
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	for _, want := range []string{
		"// Copyright (c) 2026 Steven Verhelle (enqack)",
		"// This Source Code Form is subject to the terms of the Mozilla Public",
		"// License, v. 2.0. If a copy of the MPL was not distributed with this",
		"// file, You can obtain one at https://mozilla.org/MPL/2.0/.",
		"// " + mplSPDX,
	} {
		if !strings.Contains(n, want) {
			t.Fatalf("notice is missing %q:\n%s", want, n)
		}
	}
	// A trailing space inside a comment survives gofmt, so it would
	// make the notice differ from itself by whitespace nobody can see
	// and an exact-match check would fail on files it had written.
	for _, line := range strings.Split(strings.TrimSuffix(n, "\n"), "\n") {
		if line != strings.TrimRight(line, " \t") {
			t.Fatalf("line has trailing whitespace: %q", line)
		}
	}
}

// TestNoticeUsesHashForScriptLanguages. Rendering a Go comment into a
// shell script produces a file whose first line is a syntax error, and
// the sweep would apply it everywhere before anyone ran a script.
func TestNoticeUsesHashForScriptLanguages(t *testing.T) {
	for _, ext := range []string{".py", ".sh", ".nix"} {
		n, err := testLicense().Notice(ext)
		if err != nil {
			t.Fatalf("%s: %v", ext, err)
		}
		// Asserted per LINE, not as a substring: Exhibit A carries the
		// MPL URL, whose "//" would match a whole-string search and
		// make this assertion fail against a correct notice.
		for _, line := range strings.Split(strings.TrimSuffix(n, "\n"), "\n") {
			if strings.HasPrefix(line, "//") {
				t.Fatalf("%s rendered a Go comment line %q:\n%s", ext, line, n)
			}
		}
		if !strings.HasPrefix(n, "# Copyright") {
			t.Fatalf("%s did not render a hash comment:\n%s", ext, n)
		}
	}
}
